# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/george/GGUI

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/george/GGUI

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip

.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/george/GGUI/CMakeFiles /home/george/GGUI/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/george/GGUI/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gcalibrator

# Build rule for target.
gcalibrator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gcalibrator
.PHONY : gcalibrator

# fast build rule for target.
gcalibrator/fast:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/build
.PHONY : gcalibrator/fast

#=============================================================================
# Target rules for targets named gptam

# Build rule for target.
gptam: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gptam
.PHONY : gptam

# fast build rule for target.
gptam/fast:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/build
.PHONY : gptam/fast

ARDriver.o: ARDriver.cpp.o

.PHONY : ARDriver.o

# target to build an object file
ARDriver.cpp.o:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/ARDriver.cpp.o
.PHONY : ARDriver.cpp.o

ARDriver.i: ARDriver.cpp.i

.PHONY : ARDriver.i

# target to preprocess a source file
ARDriver.cpp.i:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/ARDriver.cpp.i
.PHONY : ARDriver.cpp.i

ARDriver.s: ARDriver.cpp.s

.PHONY : ARDriver.s

# target to generate assembly for a file
ARDriver.cpp.s:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/ARDriver.cpp.s
.PHONY : ARDriver.cpp.s

ATANCamera.o: ATANCamera.cpp.o

.PHONY : ATANCamera.o

# target to build an object file
ATANCamera.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/ATANCamera.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/ATANCamera.cpp.o
.PHONY : ATANCamera.cpp.o

ATANCamera.i: ATANCamera.cpp.i

.PHONY : ATANCamera.i

# target to preprocess a source file
ATANCamera.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/ATANCamera.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/ATANCamera.cpp.i
.PHONY : ATANCamera.cpp.i

ATANCamera.s: ATANCamera.cpp.s

.PHONY : ATANCamera.s

# target to generate assembly for a file
ATANCamera.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/ATANCamera.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/ATANCamera.cpp.s
.PHONY : ATANCamera.cpp.s

CalibCornerPatch.o: CalibCornerPatch.cpp.o

.PHONY : CalibCornerPatch.o

# target to build an object file
CalibCornerPatch.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/CalibCornerPatch.cpp.o
.PHONY : CalibCornerPatch.cpp.o

CalibCornerPatch.i: CalibCornerPatch.cpp.i

.PHONY : CalibCornerPatch.i

# target to preprocess a source file
CalibCornerPatch.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/CalibCornerPatch.cpp.i
.PHONY : CalibCornerPatch.cpp.i

CalibCornerPatch.s: CalibCornerPatch.cpp.s

.PHONY : CalibCornerPatch.s

# target to generate assembly for a file
CalibCornerPatch.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/CalibCornerPatch.cpp.s
.PHONY : CalibCornerPatch.cpp.s

CalibImage.o: CalibImage.cpp.o

.PHONY : CalibImage.o

# target to build an object file
CalibImage.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/CalibImage.cpp.o
.PHONY : CalibImage.cpp.o

CalibImage.i: CalibImage.cpp.i

.PHONY : CalibImage.i

# target to preprocess a source file
CalibImage.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/CalibImage.cpp.i
.PHONY : CalibImage.cpp.i

CalibImage.s: CalibImage.cpp.s

.PHONY : CalibImage.s

# target to generate assembly for a file
CalibImage.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/CalibImage.cpp.s
.PHONY : CalibImage.cpp.s

CameraCalibrator.o: CameraCalibrator.cpp.o

.PHONY : CameraCalibrator.o

# target to build an object file
CameraCalibrator.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/CameraCalibrator.cpp.o
.PHONY : CameraCalibrator.cpp.o

CameraCalibrator.i: CameraCalibrator.cpp.i

.PHONY : CameraCalibrator.i

# target to preprocess a source file
CameraCalibrator.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/CameraCalibrator.cpp.i
.PHONY : CameraCalibrator.cpp.i

CameraCalibrator.s: CameraCalibrator.cpp.s

.PHONY : CameraCalibrator.s

# target to generate assembly for a file
CameraCalibrator.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/CameraCalibrator.cpp.s
.PHONY : CameraCalibrator.cpp.s

EyeGame.o: EyeGame.cpp.o

.PHONY : EyeGame.o

# target to build an object file
EyeGame.cpp.o:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/EyeGame.cpp.o
.PHONY : EyeGame.cpp.o

EyeGame.i: EyeGame.cpp.i

.PHONY : EyeGame.i

# target to preprocess a source file
EyeGame.cpp.i:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/EyeGame.cpp.i
.PHONY : EyeGame.cpp.i

EyeGame.s: EyeGame.cpp.s

.PHONY : EyeGame.s

# target to generate assembly for a file
EyeGame.cpp.s:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/EyeGame.cpp.s
.PHONY : EyeGame.cpp.s

FAST/fast_10_detect.o: FAST/fast_10_detect.cpp.o

.PHONY : FAST/fast_10_detect.o

# target to build an object file
FAST/fast_10_detect.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_10_detect.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_10_detect.cpp.o
.PHONY : FAST/fast_10_detect.cpp.o

FAST/fast_10_detect.i: FAST/fast_10_detect.cpp.i

.PHONY : FAST/fast_10_detect.i

# target to preprocess a source file
FAST/fast_10_detect.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_10_detect.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_10_detect.cpp.i
.PHONY : FAST/fast_10_detect.cpp.i

FAST/fast_10_detect.s: FAST/fast_10_detect.cpp.s

.PHONY : FAST/fast_10_detect.s

# target to generate assembly for a file
FAST/fast_10_detect.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_10_detect.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_10_detect.cpp.s
.PHONY : FAST/fast_10_detect.cpp.s

FAST/fast_10_score.o: FAST/fast_10_score.cpp.o

.PHONY : FAST/fast_10_score.o

# target to build an object file
FAST/fast_10_score.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_10_score.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_10_score.cpp.o
.PHONY : FAST/fast_10_score.cpp.o

FAST/fast_10_score.i: FAST/fast_10_score.cpp.i

.PHONY : FAST/fast_10_score.i

# target to preprocess a source file
FAST/fast_10_score.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_10_score.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_10_score.cpp.i
.PHONY : FAST/fast_10_score.cpp.i

FAST/fast_10_score.s: FAST/fast_10_score.cpp.s

.PHONY : FAST/fast_10_score.s

# target to generate assembly for a file
FAST/fast_10_score.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_10_score.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_10_score.cpp.s
.PHONY : FAST/fast_10_score.cpp.s

FAST/fast_11_detect.o: FAST/fast_11_detect.cpp.o

.PHONY : FAST/fast_11_detect.o

# target to build an object file
FAST/fast_11_detect.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_11_detect.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_11_detect.cpp.o
.PHONY : FAST/fast_11_detect.cpp.o

FAST/fast_11_detect.i: FAST/fast_11_detect.cpp.i

.PHONY : FAST/fast_11_detect.i

# target to preprocess a source file
FAST/fast_11_detect.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_11_detect.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_11_detect.cpp.i
.PHONY : FAST/fast_11_detect.cpp.i

FAST/fast_11_detect.s: FAST/fast_11_detect.cpp.s

.PHONY : FAST/fast_11_detect.s

# target to generate assembly for a file
FAST/fast_11_detect.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_11_detect.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_11_detect.cpp.s
.PHONY : FAST/fast_11_detect.cpp.s

FAST/fast_11_score.o: FAST/fast_11_score.cpp.o

.PHONY : FAST/fast_11_score.o

# target to build an object file
FAST/fast_11_score.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_11_score.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_11_score.cpp.o
.PHONY : FAST/fast_11_score.cpp.o

FAST/fast_11_score.i: FAST/fast_11_score.cpp.i

.PHONY : FAST/fast_11_score.i

# target to preprocess a source file
FAST/fast_11_score.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_11_score.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_11_score.cpp.i
.PHONY : FAST/fast_11_score.cpp.i

FAST/fast_11_score.s: FAST/fast_11_score.cpp.s

.PHONY : FAST/fast_11_score.s

# target to generate assembly for a file
FAST/fast_11_score.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_11_score.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_11_score.cpp.s
.PHONY : FAST/fast_11_score.cpp.s

FAST/fast_12_detect.o: FAST/fast_12_detect.cpp.o

.PHONY : FAST/fast_12_detect.o

# target to build an object file
FAST/fast_12_detect.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_12_detect.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_12_detect.cpp.o
.PHONY : FAST/fast_12_detect.cpp.o

FAST/fast_12_detect.i: FAST/fast_12_detect.cpp.i

.PHONY : FAST/fast_12_detect.i

# target to preprocess a source file
FAST/fast_12_detect.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_12_detect.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_12_detect.cpp.i
.PHONY : FAST/fast_12_detect.cpp.i

FAST/fast_12_detect.s: FAST/fast_12_detect.cpp.s

.PHONY : FAST/fast_12_detect.s

# target to generate assembly for a file
FAST/fast_12_detect.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_12_detect.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_12_detect.cpp.s
.PHONY : FAST/fast_12_detect.cpp.s

FAST/fast_12_score.o: FAST/fast_12_score.cpp.o

.PHONY : FAST/fast_12_score.o

# target to build an object file
FAST/fast_12_score.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_12_score.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_12_score.cpp.o
.PHONY : FAST/fast_12_score.cpp.o

FAST/fast_12_score.i: FAST/fast_12_score.cpp.i

.PHONY : FAST/fast_12_score.i

# target to preprocess a source file
FAST/fast_12_score.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_12_score.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_12_score.cpp.i
.PHONY : FAST/fast_12_score.cpp.i

FAST/fast_12_score.s: FAST/fast_12_score.cpp.s

.PHONY : FAST/fast_12_score.s

# target to generate assembly for a file
FAST/fast_12_score.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_12_score.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_12_score.cpp.s
.PHONY : FAST/fast_12_score.cpp.s

FAST/fast_7_detect.o: FAST/fast_7_detect.cpp.o

.PHONY : FAST/fast_7_detect.o

# target to build an object file
FAST/fast_7_detect.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_7_detect.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_7_detect.cpp.o
.PHONY : FAST/fast_7_detect.cpp.o

FAST/fast_7_detect.i: FAST/fast_7_detect.cpp.i

.PHONY : FAST/fast_7_detect.i

# target to preprocess a source file
FAST/fast_7_detect.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_7_detect.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_7_detect.cpp.i
.PHONY : FAST/fast_7_detect.cpp.i

FAST/fast_7_detect.s: FAST/fast_7_detect.cpp.s

.PHONY : FAST/fast_7_detect.s

# target to generate assembly for a file
FAST/fast_7_detect.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_7_detect.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_7_detect.cpp.s
.PHONY : FAST/fast_7_detect.cpp.s

FAST/fast_7_score.o: FAST/fast_7_score.cpp.o

.PHONY : FAST/fast_7_score.o

# target to build an object file
FAST/fast_7_score.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_7_score.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_7_score.cpp.o
.PHONY : FAST/fast_7_score.cpp.o

FAST/fast_7_score.i: FAST/fast_7_score.cpp.i

.PHONY : FAST/fast_7_score.i

# target to preprocess a source file
FAST/fast_7_score.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_7_score.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_7_score.cpp.i
.PHONY : FAST/fast_7_score.cpp.i

FAST/fast_7_score.s: FAST/fast_7_score.cpp.s

.PHONY : FAST/fast_7_score.s

# target to generate assembly for a file
FAST/fast_7_score.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_7_score.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_7_score.cpp.s
.PHONY : FAST/fast_7_score.cpp.s

FAST/fast_8_detect.o: FAST/fast_8_detect.cpp.o

.PHONY : FAST/fast_8_detect.o

# target to build an object file
FAST/fast_8_detect.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_8_detect.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_8_detect.cpp.o
.PHONY : FAST/fast_8_detect.cpp.o

FAST/fast_8_detect.i: FAST/fast_8_detect.cpp.i

.PHONY : FAST/fast_8_detect.i

# target to preprocess a source file
FAST/fast_8_detect.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_8_detect.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_8_detect.cpp.i
.PHONY : FAST/fast_8_detect.cpp.i

FAST/fast_8_detect.s: FAST/fast_8_detect.cpp.s

.PHONY : FAST/fast_8_detect.s

# target to generate assembly for a file
FAST/fast_8_detect.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_8_detect.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_8_detect.cpp.s
.PHONY : FAST/fast_8_detect.cpp.s

FAST/fast_8_score.o: FAST/fast_8_score.cpp.o

.PHONY : FAST/fast_8_score.o

# target to build an object file
FAST/fast_8_score.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_8_score.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_8_score.cpp.o
.PHONY : FAST/fast_8_score.cpp.o

FAST/fast_8_score.i: FAST/fast_8_score.cpp.i

.PHONY : FAST/fast_8_score.i

# target to preprocess a source file
FAST/fast_8_score.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_8_score.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_8_score.cpp.i
.PHONY : FAST/fast_8_score.cpp.i

FAST/fast_8_score.s: FAST/fast_8_score.cpp.s

.PHONY : FAST/fast_8_score.s

# target to generate assembly for a file
FAST/fast_8_score.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_8_score.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_8_score.cpp.s
.PHONY : FAST/fast_8_score.cpp.s

FAST/fast_9_detect.o: FAST/fast_9_detect.cpp.o

.PHONY : FAST/fast_9_detect.o

# target to build an object file
FAST/fast_9_detect.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_9_detect.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_9_detect.cpp.o
.PHONY : FAST/fast_9_detect.cpp.o

FAST/fast_9_detect.i: FAST/fast_9_detect.cpp.i

.PHONY : FAST/fast_9_detect.i

# target to preprocess a source file
FAST/fast_9_detect.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_9_detect.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_9_detect.cpp.i
.PHONY : FAST/fast_9_detect.cpp.i

FAST/fast_9_detect.s: FAST/fast_9_detect.cpp.s

.PHONY : FAST/fast_9_detect.s

# target to generate assembly for a file
FAST/fast_9_detect.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_9_detect.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_9_detect.cpp.s
.PHONY : FAST/fast_9_detect.cpp.s

FAST/fast_9_score.o: FAST/fast_9_score.cpp.o

.PHONY : FAST/fast_9_score.o

# target to build an object file
FAST/fast_9_score.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_9_score.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_9_score.cpp.o
.PHONY : FAST/fast_9_score.cpp.o

FAST/fast_9_score.i: FAST/fast_9_score.cpp.i

.PHONY : FAST/fast_9_score.i

# target to preprocess a source file
FAST/fast_9_score.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_9_score.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_9_score.cpp.i
.PHONY : FAST/fast_9_score.cpp.i

FAST/fast_9_score.s: FAST/fast_9_score.cpp.s

.PHONY : FAST/fast_9_score.s

# target to generate assembly for a file
FAST/fast_9_score.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_9_score.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_9_score.cpp.s
.PHONY : FAST/fast_9_score.cpp.s

FAST/fast_corner.o: FAST/fast_corner.cpp.o

.PHONY : FAST/fast_corner.o

# target to build an object file
FAST/fast_corner.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_corner.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_corner.cpp.o
.PHONY : FAST/fast_corner.cpp.o

FAST/fast_corner.i: FAST/fast_corner.cpp.i

.PHONY : FAST/fast_corner.i

# target to preprocess a source file
FAST/fast_corner.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_corner.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_corner.cpp.i
.PHONY : FAST/fast_corner.cpp.i

FAST/fast_corner.s: FAST/fast_corner.cpp.s

.PHONY : FAST/fast_corner.s

# target to generate assembly for a file
FAST/fast_corner.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/fast_corner.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/fast_corner.cpp.s
.PHONY : FAST/fast_corner.cpp.s

FAST/nonmax_suppression.o: FAST/nonmax_suppression.cpp.o

.PHONY : FAST/nonmax_suppression.o

# target to build an object file
FAST/nonmax_suppression.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/nonmax_suppression.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/nonmax_suppression.cpp.o
.PHONY : FAST/nonmax_suppression.cpp.o

FAST/nonmax_suppression.i: FAST/nonmax_suppression.cpp.i

.PHONY : FAST/nonmax_suppression.i

# target to preprocess a source file
FAST/nonmax_suppression.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/nonmax_suppression.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/nonmax_suppression.cpp.i
.PHONY : FAST/nonmax_suppression.cpp.i

FAST/nonmax_suppression.s: FAST/nonmax_suppression.cpp.s

.PHONY : FAST/nonmax_suppression.s

# target to generate assembly for a file
FAST/nonmax_suppression.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/FAST/nonmax_suppression.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/FAST/nonmax_suppression.cpp.s
.PHONY : FAST/nonmax_suppression.cpp.s

GCVD/GLText.o: GCVD/GLText.cpp.o

.PHONY : GCVD/GLText.o

# target to build an object file
GCVD/GLText.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GCVD/GLText.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GCVD/GLText.cpp.o
.PHONY : GCVD/GLText.cpp.o

GCVD/GLText.i: GCVD/GLText.cpp.i

.PHONY : GCVD/GLText.i

# target to preprocess a source file
GCVD/GLText.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GCVD/GLText.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GCVD/GLText.cpp.i
.PHONY : GCVD/GLText.cpp.i

GCVD/GLText.s: GCVD/GLText.cpp.s

.PHONY : GCVD/GLText.s

# target to generate assembly for a file
GCVD/GLText.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GCVD/GLText.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GCVD/GLText.cpp.s
.PHONY : GCVD/GLText.cpp.s

GCVD/GLWindow.o: GCVD/GLWindow.cpp.o

.PHONY : GCVD/GLWindow.o

# target to build an object file
GCVD/GLWindow.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GCVD/GLWindow.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GCVD/GLWindow.cpp.o
.PHONY : GCVD/GLWindow.cpp.o

GCVD/GLWindow.i: GCVD/GLWindow.cpp.i

.PHONY : GCVD/GLWindow.i

# target to preprocess a source file
GCVD/GLWindow.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GCVD/GLWindow.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GCVD/GLWindow.cpp.i
.PHONY : GCVD/GLWindow.cpp.i

GCVD/GLWindow.s: GCVD/GLWindow.cpp.s

.PHONY : GCVD/GLWindow.s

# target to generate assembly for a file
GCVD/GLWindow.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GCVD/GLWindow.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GCVD/GLWindow.cpp.s
.PHONY : GCVD/GLWindow.cpp.s

GLWindow2.o: GLWindow2.cpp.o

.PHONY : GLWindow2.o

# target to build an object file
GLWindow2.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GLWindow2.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GLWindow2.cpp.o
.PHONY : GLWindow2.cpp.o

GLWindow2.i: GLWindow2.cpp.i

.PHONY : GLWindow2.i

# target to preprocess a source file
GLWindow2.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GLWindow2.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GLWindow2.cpp.i
.PHONY : GLWindow2.cpp.i

GLWindow2.s: GLWindow2.cpp.s

.PHONY : GLWindow2.s

# target to generate assembly for a file
GLWindow2.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GLWindow2.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GLWindow2.cpp.s
.PHONY : GLWindow2.cpp.s

GLWindowMenu.o: GLWindowMenu.cpp.o

.PHONY : GLWindowMenu.o

# target to build an object file
GLWindowMenu.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GLWindowMenu.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GLWindowMenu.cpp.o
.PHONY : GLWindowMenu.cpp.o

GLWindowMenu.i: GLWindowMenu.cpp.i

.PHONY : GLWindowMenu.i

# target to preprocess a source file
GLWindowMenu.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GLWindowMenu.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GLWindowMenu.cpp.i
.PHONY : GLWindowMenu.cpp.i

GLWindowMenu.s: GLWindowMenu.cpp.s

.PHONY : GLWindowMenu.s

# target to generate assembly for a file
GLWindowMenu.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/GLWindowMenu.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/GLWindowMenu.cpp.s
.PHONY : GLWindowMenu.cpp.s

Persistence/GStringUtil.o: Persistence/GStringUtil.cpp.o

.PHONY : Persistence/GStringUtil.o

# target to build an object file
Persistence/GStringUtil.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GStringUtil.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GStringUtil.cpp.o
.PHONY : Persistence/GStringUtil.cpp.o

Persistence/GStringUtil.i: Persistence/GStringUtil.cpp.i

.PHONY : Persistence/GStringUtil.i

# target to preprocess a source file
Persistence/GStringUtil.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GStringUtil.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GStringUtil.cpp.i
.PHONY : Persistence/GStringUtil.cpp.i

Persistence/GStringUtil.s: Persistence/GStringUtil.cpp.s

.PHONY : Persistence/GStringUtil.s

# target to generate assembly for a file
Persistence/GStringUtil.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GStringUtil.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GStringUtil.cpp.s
.PHONY : Persistence/GStringUtil.cpp.s

Persistence/GUI.o: Persistence/GUI.cpp.o

.PHONY : Persistence/GUI.o

# target to build an object file
Persistence/GUI.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI.cpp.o
.PHONY : Persistence/GUI.cpp.o

Persistence/GUI.i: Persistence/GUI.cpp.i

.PHONY : Persistence/GUI.i

# target to preprocess a source file
Persistence/GUI.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI.cpp.i
.PHONY : Persistence/GUI.cpp.i

Persistence/GUI.s: Persistence/GUI.cpp.s

.PHONY : Persistence/GUI.s

# target to generate assembly for a file
Persistence/GUI.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI.cpp.s
.PHONY : Persistence/GUI.cpp.s

Persistence/GUI_impl_readline.o: Persistence/GUI_impl_readline.cpp.o

.PHONY : Persistence/GUI_impl_readline.o

# target to build an object file
Persistence/GUI_impl_readline.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI_impl_readline.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI_impl_readline.cpp.o
.PHONY : Persistence/GUI_impl_readline.cpp.o

Persistence/GUI_impl_readline.i: Persistence/GUI_impl_readline.cpp.i

.PHONY : Persistence/GUI_impl_readline.i

# target to preprocess a source file
Persistence/GUI_impl_readline.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI_impl_readline.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI_impl_readline.cpp.i
.PHONY : Persistence/GUI_impl_readline.cpp.i

Persistence/GUI_impl_readline.s: Persistence/GUI_impl_readline.cpp.s

.PHONY : Persistence/GUI_impl_readline.s

# target to generate assembly for a file
Persistence/GUI_impl_readline.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI_impl_readline.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI_impl_readline.cpp.s
.PHONY : Persistence/GUI_impl_readline.cpp.s

Persistence/GUI_language.o: Persistence/GUI_language.cpp.o

.PHONY : Persistence/GUI_language.o

# target to build an object file
Persistence/GUI_language.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI_language.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI_language.cpp.o
.PHONY : Persistence/GUI_language.cpp.o

Persistence/GUI_language.i: Persistence/GUI_language.cpp.i

.PHONY : Persistence/GUI_language.i

# target to preprocess a source file
Persistence/GUI_language.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI_language.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI_language.cpp.i
.PHONY : Persistence/GUI_language.cpp.i

Persistence/GUI_language.s: Persistence/GUI_language.cpp.s

.PHONY : Persistence/GUI_language.s

# target to generate assembly for a file
Persistence/GUI_language.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI_language.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI_language.cpp.s
.PHONY : Persistence/GUI_language.cpp.s

Persistence/GUI_readline.o: Persistence/GUI_readline.cpp.o

.PHONY : Persistence/GUI_readline.o

# target to build an object file
Persistence/GUI_readline.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI_readline.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI_readline.cpp.o
.PHONY : Persistence/GUI_readline.cpp.o

Persistence/GUI_readline.i: Persistence/GUI_readline.cpp.i

.PHONY : Persistence/GUI_readline.i

# target to preprocess a source file
Persistence/GUI_readline.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI_readline.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI_readline.cpp.i
.PHONY : Persistence/GUI_readline.cpp.i

Persistence/GUI_readline.s: Persistence/GUI_readline.cpp.s

.PHONY : Persistence/GUI_readline.s

# target to generate assembly for a file
Persistence/GUI_readline.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/GUI_readline.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/GUI_readline.cpp.s
.PHONY : Persistence/GUI_readline.cpp.s

Persistence/PVars.o: Persistence/PVars.cpp.o

.PHONY : Persistence/PVars.o

# target to build an object file
Persistence/PVars.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/PVars.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/PVars.cpp.o
.PHONY : Persistence/PVars.cpp.o

Persistence/PVars.i: Persistence/PVars.cpp.i

.PHONY : Persistence/PVars.i

# target to preprocess a source file
Persistence/PVars.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/PVars.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/PVars.cpp.i
.PHONY : Persistence/PVars.cpp.i

Persistence/PVars.s: Persistence/PVars.cpp.s

.PHONY : Persistence/PVars.s

# target to generate assembly for a file
Persistence/PVars.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/PVars.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/PVars.cpp.s
.PHONY : Persistence/PVars.cpp.s

Persistence/instances.o: Persistence/instances.cpp.o

.PHONY : Persistence/instances.o

# target to build an object file
Persistence/instances.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/instances.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/instances.cpp.o
.PHONY : Persistence/instances.cpp.o

Persistence/instances.i: Persistence/instances.cpp.i

.PHONY : Persistence/instances.i

# target to preprocess a source file
Persistence/instances.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/instances.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/instances.cpp.i
.PHONY : Persistence/instances.cpp.i

Persistence/instances.s: Persistence/instances.cpp.s

.PHONY : Persistence/instances.s

# target to generate assembly for a file
Persistence/instances.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/instances.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/instances.cpp.s
.PHONY : Persistence/instances.cpp.s

Persistence/serialize.o: Persistence/serialize.cpp.o

.PHONY : Persistence/serialize.o

# target to build an object file
Persistence/serialize.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/serialize.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/serialize.cpp.o
.PHONY : Persistence/serialize.cpp.o

Persistence/serialize.i: Persistence/serialize.cpp.i

.PHONY : Persistence/serialize.i

# target to preprocess a source file
Persistence/serialize.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/serialize.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/serialize.cpp.i
.PHONY : Persistence/serialize.cpp.i

Persistence/serialize.s: Persistence/serialize.cpp.s

.PHONY : Persistence/serialize.s

# target to generate assembly for a file
Persistence/serialize.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/Persistence/serialize.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/Persistence/serialize.cpp.s
.PHONY : Persistence/serialize.cpp.s

System.o: System.cpp.o

.PHONY : System.o

# target to build an object file
System.cpp.o:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/System.cpp.o
.PHONY : System.cpp.o

System.i: System.cpp.i

.PHONY : System.i

# target to preprocess a source file
System.cpp.i:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/System.cpp.i
.PHONY : System.cpp.i

System.s: System.cpp.s

.PHONY : System.s

# target to generate assembly for a file
System.cpp.s:
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/System.cpp.s
.PHONY : System.cpp.s

VideoSource_Linux_OpenCV.o: VideoSource_Linux_OpenCV.cpp.o

.PHONY : VideoSource_Linux_OpenCV.o

# target to build an object file
VideoSource_Linux_OpenCV.cpp.o:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/VideoSource_Linux_OpenCV.cpp.o
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/VideoSource_Linux_OpenCV.cpp.o
.PHONY : VideoSource_Linux_OpenCV.cpp.o

VideoSource_Linux_OpenCV.i: VideoSource_Linux_OpenCV.cpp.i

.PHONY : VideoSource_Linux_OpenCV.i

# target to preprocess a source file
VideoSource_Linux_OpenCV.cpp.i:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/VideoSource_Linux_OpenCV.cpp.i
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/VideoSource_Linux_OpenCV.cpp.i
.PHONY : VideoSource_Linux_OpenCV.cpp.i

VideoSource_Linux_OpenCV.s: VideoSource_Linux_OpenCV.cpp.s

.PHONY : VideoSource_Linux_OpenCV.s

# target to generate assembly for a file
VideoSource_Linux_OpenCV.cpp.s:
	$(MAKE) -f CMakeFiles/gcalibrator.dir/build.make CMakeFiles/gcalibrator.dir/VideoSource_Linux_OpenCV.cpp.s
	$(MAKE) -f CMakeFiles/gptam.dir/build.make CMakeFiles/gptam.dir/VideoSource_Linux_OpenCV.cpp.s
.PHONY : VideoSource_Linux_OpenCV.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... gcalibrator"
	@echo "... gptam"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... ARDriver.o"
	@echo "... ARDriver.i"
	@echo "... ARDriver.s"
	@echo "... ATANCamera.o"
	@echo "... ATANCamera.i"
	@echo "... ATANCamera.s"
	@echo "... CalibCornerPatch.o"
	@echo "... CalibCornerPatch.i"
	@echo "... CalibCornerPatch.s"
	@echo "... CalibImage.o"
	@echo "... CalibImage.i"
	@echo "... CalibImage.s"
	@echo "... CameraCalibrator.o"
	@echo "... CameraCalibrator.i"
	@echo "... CameraCalibrator.s"
	@echo "... EyeGame.o"
	@echo "... EyeGame.i"
	@echo "... EyeGame.s"
	@echo "... FAST/fast_10_detect.o"
	@echo "... FAST/fast_10_detect.i"
	@echo "... FAST/fast_10_detect.s"
	@echo "... FAST/fast_10_score.o"
	@echo "... FAST/fast_10_score.i"
	@echo "... FAST/fast_10_score.s"
	@echo "... FAST/fast_11_detect.o"
	@echo "... FAST/fast_11_detect.i"
	@echo "... FAST/fast_11_detect.s"
	@echo "... FAST/fast_11_score.o"
	@echo "... FAST/fast_11_score.i"
	@echo "... FAST/fast_11_score.s"
	@echo "... FAST/fast_12_detect.o"
	@echo "... FAST/fast_12_detect.i"
	@echo "... FAST/fast_12_detect.s"
	@echo "... FAST/fast_12_score.o"
	@echo "... FAST/fast_12_score.i"
	@echo "... FAST/fast_12_score.s"
	@echo "... FAST/fast_7_detect.o"
	@echo "... FAST/fast_7_detect.i"
	@echo "... FAST/fast_7_detect.s"
	@echo "... FAST/fast_7_score.o"
	@echo "... FAST/fast_7_score.i"
	@echo "... FAST/fast_7_score.s"
	@echo "... FAST/fast_8_detect.o"
	@echo "... FAST/fast_8_detect.i"
	@echo "... FAST/fast_8_detect.s"
	@echo "... FAST/fast_8_score.o"
	@echo "... FAST/fast_8_score.i"
	@echo "... FAST/fast_8_score.s"
	@echo "... FAST/fast_9_detect.o"
	@echo "... FAST/fast_9_detect.i"
	@echo "... FAST/fast_9_detect.s"
	@echo "... FAST/fast_9_score.o"
	@echo "... FAST/fast_9_score.i"
	@echo "... FAST/fast_9_score.s"
	@echo "... FAST/fast_corner.o"
	@echo "... FAST/fast_corner.i"
	@echo "... FAST/fast_corner.s"
	@echo "... FAST/nonmax_suppression.o"
	@echo "... FAST/nonmax_suppression.i"
	@echo "... FAST/nonmax_suppression.s"
	@echo "... GCVD/GLText.o"
	@echo "... GCVD/GLText.i"
	@echo "... GCVD/GLText.s"
	@echo "... GCVD/GLWindow.o"
	@echo "... GCVD/GLWindow.i"
	@echo "... GCVD/GLWindow.s"
	@echo "... GLWindow2.o"
	@echo "... GLWindow2.i"
	@echo "... GLWindow2.s"
	@echo "... GLWindowMenu.o"
	@echo "... GLWindowMenu.i"
	@echo "... GLWindowMenu.s"
	@echo "... Persistence/GStringUtil.o"
	@echo "... Persistence/GStringUtil.i"
	@echo "... Persistence/GStringUtil.s"
	@echo "... Persistence/GUI.o"
	@echo "... Persistence/GUI.i"
	@echo "... Persistence/GUI.s"
	@echo "... Persistence/GUI_impl_readline.o"
	@echo "... Persistence/GUI_impl_readline.i"
	@echo "... Persistence/GUI_impl_readline.s"
	@echo "... Persistence/GUI_language.o"
	@echo "... Persistence/GUI_language.i"
	@echo "... Persistence/GUI_language.s"
	@echo "... Persistence/GUI_readline.o"
	@echo "... Persistence/GUI_readline.i"
	@echo "... Persistence/GUI_readline.s"
	@echo "... Persistence/PVars.o"
	@echo "... Persistence/PVars.i"
	@echo "... Persistence/PVars.s"
	@echo "... Persistence/instances.o"
	@echo "... Persistence/instances.i"
	@echo "... Persistence/instances.s"
	@echo "... Persistence/serialize.o"
	@echo "... Persistence/serialize.i"
	@echo "... Persistence/serialize.s"
	@echo "... System.o"
	@echo "... System.i"
	@echo "... System.s"
	@echo "... VideoSource_Linux_OpenCV.o"
	@echo "... VideoSource_Linux_OpenCV.i"
	@echo "... VideoSource_Linux_OpenCV.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

